package org.sustainability.likeherotozero.entity;

import jakarta.persistence.*;

import java.util.List;

/**
 * Entity class representing a country.
 * This class stores information about a country, including its name, code, and related emission data.
 */
@Entity
public class Country {

    /**
     * The unique identifier for the country.
     * This ID is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The name of the country.
     * This field is required and must be unique.
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * The code of the country, typically in ISO 3166-1 alpha-3 format.
     * This field is required, must be three characters long, and must be unique.
     */
    @Column(length = 3, nullable = false, unique = true)
    private String code;

    /**
     * The list of emission data associated with the country.
     * This relationship is mapped by the "country" field in the {@link EmissionData} entity.
     */
    @OneToMany(mappedBy = "country")
    private List<EmissionData> emissionData;

    /**
     * Default constructor for JPA.
     */
    public Country() {
    }

    /**
     * Gets the unique identifier of the country.
     *
     * @return the country's ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the country.
     *
     * @param id the country's ID.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the name of the country.
     *
     * @return the country's name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the country.
     *
     * @param name the country's name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the code of the country.
     *
     * @return the country's code.
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the code of the country.
     *
     * @param code the country's code.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Gets the list of emission data associated with the country.
     *
     * @return the list of {@link EmissionData}.
     */
    public List<EmissionData> getEmissionData() {
        return emissionData;
    }

    /**
     * Sets the list of emission data associated with the country.
     *
     * @param emissionData the list of {@link EmissionData} to set.
     */
    public void setEmissionData(List<EmissionData> emissionData) {
        this.emissionData = emissionData;
    }

    /**
     * Adds an emission data entry to the list and sets this country as the parent.
     *
     * @param emissionData the {@link EmissionData} to add.
     */
    public void addEmissionData(EmissionData emissionData) {
        this.emissionData.add(emissionData);
        emissionData.setCountry(this);
    }

    /**
     * Removes an emission data entry from the list and clears the country reference.
     *
     * @param emissionData the {@link EmissionData} to remove.
     */
    public void removeEmissionData(EmissionData emissionData) {
        this.emissionData.remove(emissionData);
        emissionData.setCountry(null);
    }
}